In [2]:
import pandas as pd
import numpy as np
import networkx as nx
import pickle

In [8]:
kg_path = "../../data/KG/ad_network_with_reverse_edges.pkl"

with open(kg_path, 'rb') as f:
    KG = pickle.load(f)

# Export networkx Graph to Neo4j compatible nodes.csv and edges.scv
+ in nodes.csv:
  + Neo4j requires the unique identifier column to be named :ID
  + the label column to be named :LABEL
+ in edges.csv
  + Neo4j requires :START_ID and :END_ID;
  + the edge type to be named :TYPE

In [11]:
with open(kg_path, 'rb') as f:
    KG = pickle.load(f)

# 1. Convert Nodes
nodes_data = []
for node_id, attrs in KG.nodes(data=True):
    #print(attrs)
    node_dict = {":ID": node_id}
    
    if "label" in attrs:
        node_dict[":LABEL"] = attrs.pop("label")
    
    # Add all remaining attributes as Neo4j properties
    node_dict.update(attrs)
    nodes_data.append(node_dict)

df_nodes = pd.DataFrame(nodes_data)
df_nodes.to_csv("./import/nodes.csv", index=False)
df_nodes

,:ID,:LABEL,pure,species,name,involved_genes,namespace,type,involved_other
0,"g(HGNC:""BDNF"")",Gene,NaN,9606.0,BDNF,BDNF,HGNC,Gene,NaN
1,"g(HGNC:""TP53"")",Gene,NaN,9606.0,TP53,TP53,HGNC,Gene,NaN
2,"g(HGNC:""PPP1CC"")",Gene,NaN,9606.0,PPP1CC,PPP1CC,HGNC,Gene,NaN
3,"g(HGNC:""VLDLR"")",Gene,NaN,9606.0,VLDLR,VLDLR,HGNC,Gene,NaN
4,"g(HGNC:""SLC1A2"")",Gene,NaN,9606.0,SLC1A2,SLC1A2,HGNC,Gene,NaN
...,...,...,...,...,...,...,...,...,...
3727,"composite(a(CHEBI:""fatty acid""),a(CHEBI:""icosa...",Composite,NaN,0.0,NaN,NaN,NaN,Composite,NaN
3728,"composite(p(HGNC:""IL1B""),p(HGNC:""IL6""))",Composite,NaN,0.0,NaN,NaN,NaN,Composite,NaN
3729,"composite(p(HGNC:""IL1B""),p(HGNC:""OSM""))",Composite,NaN,0.0,NaN,NaN,NaN,Composite,NaN
3730,"composite(a(CHEBI:""Ibotenic acid""),p(HGNC:""APP...",Composite,NaN,0.0,NaN,NaN,NaN,Composite,NaN
3731,"composite(p(HGNC:""TNFRSF12A""),p(HGNC:""TNFRSF25""))",Composite,NaN,0.0,NaN,NaN,NaN,Composite,NaN

In [ ]:
# 2. extract and format edges
edges_data = []
for source, target, rel, attrs in KG.edges(data=True, keys=True):
    # print(source, rel, target)
    # print(attrs)
    # break
    edge_dict = {
        ":START_ID": source,
        ":END_ID": target,
        ":TYPE": rel,
    }
         
    # Add all remaining attributes as edge properties
    edge_dict.update(attrs)
    edges_data.append(edge_dict)

df_edges = pd.DataFrame(edges_data)
df_edges.to_csv("./import/edges.csv", index=False)

print("Export complete! Files saved as 'nodes.csv' and 'edges.csv'.")
df_edges

Export complete! Files saved as 'nodes.csv' and 'edges.csv'.

,:START_ID,:END_ID,:TYPE,annotation,disease,evidence,pmid,pathway,subgraph
0,"g(HGNC:""BDNF"")","p(HGNC:""APP"",frag(""672_713""))",decreases,"{'confidence': '['Medium']', 'subgraph': '['No...",ad,"[""Using screening approaches in primary neuron...",[20007471],NaN,NaN
1,"g(HGNC:""BDNF"")","g(HGNC:""SORL1"")",increases,"{'confidence': '['Medium']', 'subgraph': '['No...",ad,"[""Using screening approaches in primary neuron...",[20007471],NaN,NaN
2,"g(HGNC:""BDNF"")","p(HGNC:""BDNF"")",increases,"{'gender': '['Female']', 'experimentalgroup': ...",ad,"[""In the hippocampus, Bdnf gene was underexpre...",[24688469],NaN,NaN
3,"g(HGNC:""BDNF"")","g(HGNC:""NRN1"")",rev_association,NaN,NaN,NaN,NaN,NaN,NaN
4,"g(HGNC:""BDNF"")","p(HGNC:""H3F3A"")",rev_association,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
15707,"composite(a(CHEBI:""Ibotenic acid""),p(HGNC:""APP...","p(HGNC:""NR4A2"")",decreases,NaN,ad,"[""Besides, we observed that oA42i (oligomeric ...",[25274193],NaN,NaN
15708,"composite(a(CHEBI:""Ibotenic acid""),p(HGNC:""APP...","p(HGNC:""ADAM10"")",decreases,NaN,ad,"[""Besides, we observed that oA42i (oligomeric ...",[25274193],NaN,NaN
15709,"composite(a(CHEBI:""Ibotenic acid""),p(HGNC:""APP...","p(HGNC:""FOS"")",decreases,NaN,ad,"[""Besides, we observed that oA42i (oligomeric ...",[25274193],NaN,NaN
15710,"composite(a(CHEBI:""Ibotenic acid""),p(HGNC:""APP...","p(HGNC:""SIRT1"")",decreases,NaN,ad,"[""Besides, we observed that oA42i (oligomeric ...",[25274193],NaN,NaN
15711,"composite(p(HGNC:""TNFRSF12A""),p(HGNC:""TNFRSF25""))","path(MESH:""Intervertebral Disc Degeneration"")",association,{'subgraph': '['Tumor necrosis factor subgraph...,ad,"[""Remarkably, TWEAK and its receptors, fibrobl...",[26907852],NaN,NaN