In [ ]:
import os
import sys
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib_venn import venn2

try:
    base_dir = os.path.dirname(os.path.abspath(__file__))
except NameError:
    base_dir = os.getcwd()
sys.path.append(os.path.dirname(base_dir))

from data_processing.pyg_graph_generator import *
from data_processing.sample_scoring import *

In [5]:
ppi_kg = pd.read_csv("../CLEP_repeat/clep_resources/Datasets/ADNI/threshold/data/ppi-kg.edgelist", sep='\t')
ppi_kg

         source     relation  target
0          USP7    decreases    TP53
1           SFN  association   SYNJ2
2          PAK1  association  PIK3CB
3         BIRC6  association  MAP2K1
4         AXIN1  association   SMAD7
...         ...          ...     ...
209814    XRCC5    increases   ATRIP
209815  ZFYVE16    regulates   SMAD4
209816   ZNF655    increases     SP1
209817   ZNF655    increases    FADD
209818   ZNF655    increases    TP53

[209819 rows x 3 columns]

In [16]:
PPI_Proteins = set(ppi_kg['source'].unique()) | set(ppi_kg['target'].unique())
len(PPI_Proteins)

8911

### ADNI data in CLEP

In [7]:
sample_scoring = pd.read_csv("../CLEP_repeat/clep_resources/Datasets/ADNI/kge_model/results/sample_scoring.tsv", sep='\t', index_col=0)
sample_scoring

,HIST1H3G,HIST1H3G.1,HIST1H3G.2,TNFAIP8L1,OTOP2,C17ORF78,LINC01098,SAMD7,ARRDC5,C1ORF173,...,H3F3AP4.2,RNA18S5,RNA45S5,RNA18S5.1,RNA45S5.1,RNA18S5.2,RNA45S5.2,RNA28S5,RNA45S5.3,label
116_S_1249,0,0,0,-1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
037_S_4410,0,0,0,-1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
006_S_4153,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
116_S_1232,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
099_S_4205,-1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
009_S_2381,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
053_S_4557,0,0,0,0,0,0,-1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
073_S_4300,0,0,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,1
041_S_4014,0,0,0,0,0,0,0,-1,0,0,...,0,0,0,0,0,0,0,0,0,0
007_S_0101,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [20]:
GE_clep = set(sample_scoring.columns)
len(GE_clep)

49945

In [8]:
sample_label_map = sample_scoring['label'].to_dict()
sample_label_map

{'116_S_1249': 0,
 '037_S_4410': 0,
 '006_S_4153': 1,
 '116_S_1232': 0,
 '099_S_4205': 1,
 '007_S_4467': 1,
 '128_S_0205': 1,
 '003_S_2374': 1,
 '036_S_4491': 0,
 '098_S_4059': 1,
 '031_S_2018': 1,
 '002_S_4654': 1,
 '019_S_4285': 1,
 '141_S_4426': 1,
 '067_S_4072': 1,
 '037_S_4308': 0,
 '041_S_4200': 0,
 '128_S_0200': 1,
 '129_S_4220': 1,
 '018_S_4313': 0,
 '067_S_0257': 0,
 '029_S_1218': 1,
 '141_S_4053': 1,
 '136_S_4408': 1,
 '021_S_2142': 1,
 '114_S_4404': 1,
 '116_S_4167': 1,
 '116_S_4209': 1,
 '073_S_4360': 1,
 '072_S_4539': 1,
 '007_S_2394': 1,
 '128_S_1407': 1,
 '109_S_2200': 1,
 '057_S_1269': 1,
 '022_S_1097': 1,
 '010_S_0420': 0,
 '072_S_2083': 1,
 '014_S_4615': 1,
 '073_S_4259': 1,
 '002_S_1268': 1,
 '024_S_0985': 0,
 '073_S_4382': 0,
 '127_S_0684': 0,
 '067_S_4310': 1,
 '035_S_0156': 0,
 '041_S_4427': 0,
 '127_S_0622': 0,
 '129_S_4396': 0,
 '019_S_4477': 1,
 '002_S_1261': 0,
 '041_S_4271': 1,
 '003_S_1122': 1,
 '941_S_2060': 1,
 '012_S_4094': 1,
 '129_S_4287': 1,
 '135_S_4356': 1,
 '136_S_0186': 0,
 '098_S_4050': 0,
 '073_S_4155': 0,
 '073_S_2182': 1,
 '013_S_4580': 0,
 '100_S_1286': 0,
 '072_S_2027': 1,
 '099_S_4463': 1,
 '094_S_2201': 1,
 '099_S_4565': 1,
 '129_S_1246': 1,
 '016_S_4097': 0,
 '023_S_0376': 1,
 '024_S_4084': 0,
 '031_S_4496': 0,
 '014_S_4079': 1,
 '072_S_4102': 1,
 '032_S_0677': 0,
 '002_S_4270': 0,
 '127_S_0259': 0,
 '041_S_4510': 1,
 '037_S_0467': 0,
 '006_S_4192': 1,
 '137_S_0668': 1,
 '002_S_2073': 1,
 '123_S_4526': 1,
 '003_S_4555': 0,
 '010_S_4442': 0,
 '035_S_4082': 0,
 '037_S_4015': 1,
 '128_S_4636': 1,
 '041_S_4513': 1,
 '098_S_4275': 0,
 '068_S_4174': 0,
 '024_S_1063': 0,
 '068_S_0473': 0,
 '073_S_4540': 1,
 '010_S_4345': 0,
 '041_S_1010': 1,
 '018_S_2180': 1,
 '014_S_0558': 0,
 '068_S_2171': 1,
 '029_S_0914': 1,
 '033_S_0923': 0,
 '130_S_4660': 1,
 '014_S_0548': 0,
 '041_S_4004': 1,
 '129_S_2332': 1,
 '137_S_4331': 1,
 '027_S_0835': 1,
 '031_S_1066': 1,
 '126_S_2405': 1,
 '128_S_4607': 0,
 '003_S_4136': 1,
 '013_S_1186': 1,
 '052_S_4626': 1,
 '012_S_4545': 0,
 '006_S_4150': 0,
 '007_S_1206': 0,
 '036_S_0673': 1,
 '032_S_2247': 1,
 '114_S_1106': 1,
 '128_S_4609': 0,
 '082_S_2307': 1,
 '027_S_2336': 1,
 '007_S_2106': 1,
 '033_S_0922': 1,
 '013_S_4268': 1,
 '007_S_4620': 0,
 '014_S_2185': 1,
 '031_S_4476': 1,
 '123_S_4170': 1,
 '141_S_0767': 0,
 '941_S_4255': 0,
 '002_S_4213': 0,
 '003_S_4354': 1,
 '051_S_1331': 1,
 '014_S_4577': 0,
 '130_S_0285': 1,
 '051_S_1123': 0,
 '014_S_4080': 0,
 '099_S_4202': 1,
 '099_S_2042': 1,
 '153_S_4297': 1,
 '094_S_4089': 1,
 '029_S_4290': 0,
 '005_S_4168': 1,
 '072_S_4613': 1,
 '033_S_4505': 0,
 '023_S_0625': 1,
 '123_S_0298': 0,
 '051_S_1072': 1,
 '072_S_2116': 1,
 '070_S_4692': 1,
 '013_S_2324': 1,
 '137_S_4596': 1,
 '109_S_4499': 0,
 '009_S_4612': 0,
 '099_S_0291': 1,
 '023_S_0126': 1,
 '068_S_4340': 0,
 '094_S_4434': 1,
 '023_S_4501': 1,
 '023_S_2068': 1,
 '116_S_4453': 0,
 '011_S_4366': 1,
 '082_S_2121': 1,
 '135_S_4281': 1,
 '135_S_4657': 1,
 '006_S_4346': 1,
 '012_S_4026': 0,
 '016_S_4591': 1,
 '036_S_2378': 1,
 '127_S_0925': 1,
 '006_S_4363': 1,
 '114_S_0166': 0,
 '127_S_4198': 0,
 '029_S_0845': 0,
 '024_S_4280': 1,
 '007_S_4488': 0,
 '067_S_2196': 1,
 '012_S_4128': 1,
 '002_S_4171': 1,
 '129_S_4371': 0,
 '073_S_4312': 1,
 '099_S_0352': 0,
 '021_S_4245': 1,
 '005_S_4185': 1,
 '003_S_0908': 1,
 '130_S_4250': 1,
 '052_S_1250': 0,
 '127_S_2234': 1,
 '035_S_4414': 1,
 '031_S_4474': 0,
 '007_S_4516': 0,
 '130_S_2391': 1,
 '027_S_1045': 1,
 '137_S_0972': 0,
 '941_S_4376': 0,
 '006_S_4515': 1,
 '067_S_4054': 1,
 '036_S_1023': 0,
 '068_S_4061': 1,
 '098_S_0171': 0,
 '114_S_0378': 1,
 '098_S_4506': 0,
 '127_S_4210': 1,
 '094_S_2216': 1,
 '127_S_4645': 0,
 '037_S_0303': 0,
 '016_S_0359': 0,
 '033_S_4177': 0,
 '127_S_2213': 1,
 '072_S_4103': 0,
 '003_S_4119': 0,
 '016_S_0702': 1,
 '116_S_4625': 1,
 '073_S_0746': 1,
 '067_S_2301': 1,
 '023_S_0042': 1,
 '072_S_4445': 1,
 '023_S_4020': 0,
 '032_S_4348': 0,
 '035_S_4256': 1,
 '082_S_1256': 0,
 '018_S_4257': 0,
 '021_S_4276': 0,
 '137_S_4351': 1,
 '022_S_1351': 1,
 '099_S_4498': 1,
 '141_S_1255': 1,
 '098_S_4018': 0,
 '116_S_0834': 1,
 '128_S_0272': 0,
 '031_S_4032': 0,
 '052_S_0671': 1,
 '100_S_4469': 0,
 '127_S_1032': 1,
 '036_S_2380': 1,
 '035_S_2199': 1,
 '032_S_0479': 0,
 '128_S_2011': 1,
 '137_S_4672': 1,
 '024_S_4392': 1,
 '010_S_0161': 1,
 '022_S_4320': 0,
 '005_S_0553': 0,
 '068_S_2168': 1,
 '007_S_0068': 0,
 '002_S_4225': 0,
 '037_S_4030': 1,
 '116_S_4635': 1,
 '033_S_4176': 0,
 '128_S_1406': 1,
 '072_S_2093': 1,
 '072_S_4522': 1,
 '021_S_0337': 0,
 '023_S_4502': 1,
 '072_S_4390': 1,
 '021_S_4254': 0,
 '123_S_0072': 0,
 '011_S_4075': 0,
 '100_S_0035': 0,
 '057_S_2398': 1,
 '018_S_4400': 0,
 '137_S_4299': 1,
 '002_S_4447': 1,
 '021_S_0159': 0,
 '941_S_1202': 0,
 '019_S_4293': 1,
 '073_S_2225': 1,
 '068_S_2194': 1,
 '011_S_4222': 0,
 '023_S_0217': 1,
 '014_S_0519': 0,
 '014_S_4328': 1,
 '009_S_4388': 0,
 '023_S_4115': 1,
 '023_S_0031': 0,
 '073_S_4559': 0,
 '032_S_2119': 1,
 '127_S_4240': 1,
 '009_S_2208': 1,
 '022_S_4173': 0,
 '014_S_4576': 0,
 '002_S_4237': 1,
 '126_S_0680': 0,
 '014_S_4093': 0,
 '073_S_4443': 1,
 '023_S_1046': 1,
 '137_S_0301': 0,
 '068_S_0872': 1,
 '002_S_1280': 0,
 '011_S_4547': 1,
 '023_S_0058': 0,
 '009_S_4337': 0,
 '041_S_4143': 1,
 '099_S_4022': 1,
 '029_S_4384': 0,
 '114_S_1118': 1,
 '014_S_2308': 1,
 '128_S_2002': 1,
 '141_S_0717': 0,
 '005_S_4707': 1,
 '130_S_4294': 1,
 '116_S_4092': 0,
 '005_S_0610': 0,
 '037_S_0150': 1,
 '073_S_4552': 0,
 '136_S_4433': 0,
 '032_S_2240': 1,
 '022_S_0130': 0,
 '128_S_0225': 1,
 '941_S_4292': 0,
 '098_S_4003': 0,
 '072_S_2026': 1,
 '153_S_2148': 1,
 '007_S_4611': 1,
 '116_S_4010': 0,
 '099_S_2146': 1,
 '127_S_0260': 0,
 '006_S_0731': 0,
 '037_S_4146': 1,
 '067_S_2195': 1,
 '023_S_0887': 1,
 '072_S_2164': 1,
 '068_S_4274': 1,
 '033_S_1116': 1,
 '126_S_4514': 1,
 '037_S_0588': 1,
 '027_S_0307': 1,
 '123_S_0108': 1,
 '072_S_2037': 1,
 '128_S_4653': 1,
 '011_S_2274': 1,
 '073_S_4614': 1,
 '029_S_0824': 0,
 '068_S_2184': 1,
 '082_S_4090': 0,
 '067_S_2304': 1,
 '073_S_4393': 0,
 '053_S_0919': 1,
 '035_S_4114': 1,
 '037_S_1078': 1,
 '002_S_4473': 1,
 '114_S_0173': 0,
 '027_S_1387': 1,
 '011_S_0008': 0,
 '128_S_2123': 1,
 '041_S_4629': 1,
 '006_S_4449': 0,
 '002_S_1155': 1,
 '130_S_4405': 1,
 '007_S_4272': 1,
 '123_S_4127': 1,
 '023_S_0926': 0,
 '128_S_2151': 1,
 '067_S_0059': 0,
 '136_S_0107': 1,
 '027_S_0256': 1,
 '123_S_1300': 1,
 '941_S_4036': 1,
 '127_S_4500': 1,
 '072_S_4465': 1,
 '009_S_4564': 1,
 '141_S_0697': 1,
 '009_S_4543': 1,
 '941_S_4377': 1,
 '007_S_4387': 0,
 '141_S_4232': 1,
 '031_S_4021': 0,
 '127_S_4604': 0,
 '011_S_1282': 1,
 '011_S_4235': 1,
 '014_S_0563': 1,
 '153_S_4372': 0,
 '029_S_4327': 1,
 '041_S_1425': 1,
 '032_S_0214': 1,
 '128_S_2045': 1,
 '010_S_0419': 0,
 '022_S_2087': 1,
 '126_S_4686': 1,
 '041_S_1260': 1,
 '031_S_4005': 1,
 '073_S_0311': 0,
 '073_S_4311': 1,
 '023_S_4243': 1,
 '094_S_4234': 0,
 '022_S_4266': 0,
 '068_S_2316': 1,
 '003_S_4350': 0,
 '014_S_0169': 1,
 '128_S_0229': 0,
 '029_S_2376': 1,
 '021_S_2124': 1,
 '007_S_1222': 0,
 '035_S_4464': 0,
 '098_S_2079': 1,
 '032_S_4277': 0,
 '035_S_0292': 1,
 '068_S_4431': 1,
 '016_S_4121': 0,
 '003_S_4081': 0,
 '116_S_4199': 1,
 '128_S_2003': 1,
 '130_S_4415': 1,
 '073_S_4403': 1,
 '037_S_0566': 1,
 '005_S_2390': 1,
 '099_S_1034': 1,
 '021_S_2125': 1,
 '023_S_4122': 1,
 '067_S_4212': 1,
 '072_S_4391': 0,
 '082_S_4224': 0,
 '141_S_4160': 1,
 '003_S_0981': 0,
 '021_S_4335': 0,
 '027_S_2219': 1,
 '116_S_0649': 1,
 '128_S_0522': 0,
 '137_S_4482': 0,
 '128_S_4553': 1,
 '013_S_4395': 1,
 '016_S_2284': 1,
 '007_S_0128': 1,
 '109_S_2237': 1,
 '019_S_4252': 1,
 '033_S_1016': 0,
 '126_S_4458': 1,
 '072_S_2072': 1,
 '128_S_1408': 1,
 '109_S_2278': 1,
 '073_S_2190': 1,
 '003_S_4152': 1,
 '126_S_0605': 0,
 '116_S_1271': 1,
 '137_S_4211': 1,
 '033_S_4179': 0,
 '036_S_4430': 1,
 '006_S_0498': 0,
 '153_S_4077': 1,
 '082_S_2099': 1,
 '023_S_1190': 0,
 '126_S_4494': 1,
 '072_S_4007': 1,
 '011_S_1080': 1,
 '018_S_4349': 0,
 '035_S_2074': 1,
 '011_S_0002': 0,
 '130_S_4468': 1,
 '123_S_2363': 1,
 '031_S_0867': 1,
 '032_S_4386': 0,
 '033_S_0514': 1,
 '014_S_0557': 1,
 '123_S_2055': 1,
 '128_S_0230': 0,
 '099_S_4475': 1,
 '094_S_4162': 1,
 '052_S_0989': 1,
 '035_S_4582': 1,
 '135_S_4446': 0,
 '018_S_2155': 1,
 '098_S_0160': 1,
 '128_S_2220': 1,
 '032_S_4429': 0,
 '035_S_2061': 1,
 '098_S_0269': 1,
 '009_S_4530': 1,
 '099_S_2205': 1,
 '007_S_4568': 1,
 '033_S_4508': 0,
 '094_S_4560': 0,
 '141_S_4438': 1,
 '013_S_2389': 1,
 '116_S_0382': 0,
 '016_S_4353': 1,
 '127_S_1427': 1,
 '052_S_1352': 1,
 '016_S_1326': 1,
 '007_S_2058': 1,
 '057_S_1007': 1,
 '068_S_2315': 1,
 '153_S_4621': 1,
 '098_S_2047': 1,
 '099_S_4086': 0,
 '037_S_4001': 1,
 '003_S_4373': 1,
 '128_S_0135': 1,
 '041_S_0679': 1,
 '022_S_4291': 0,
 '082_S_4208': 0,
 '003_S_1074': 1,
 '128_S_0545': 0,
 '068_S_4424': 0,
 '094_S_4503': 0,
 '051_S_1131': 1,
 '021_S_0276': 1,
 '127_S_0112': 1,
 '002_S_4219': 1,
 '051_S_1040': 1,
 '031_S_4203': 1,
 '018_S_0142': 1,
 '082_S_4428': 0,
 '007_S_4637': 0,
 '100_S_0047': 0,
 '009_S_0842': 0,
 '041_S_4041': 0,
 '082_S_4244': 1,
 '037_S_4302': 1,
 '127_S_4197': 1,
 '073_S_2264': 1,
 '023_S_4034': 1,
 '098_S_4095': 1,
 '009_S_1030': 1,
 '072_S_4394': 1,
 '002_S_4229': 1,
 '021_S_2150': 1,
 '116_S_4175': 1,
 '024_S_4169': 1,
 '123_S_4096': 1,
 '012_S_4012': 1,
 '029_S_4307': 1,
 '002_S_4521': 1,
 '067_S_4184': 1,
 '023_S_4241': 1,
 '031_S_0294': 1,
 '098_S_0172': 0,
 '032_S_1169': 0,
 '029_S_0878': 1,
 '099_S_0051': 1,
 '002_S_0685': 0,
 '012_S_4643': 0,
 '027_S_0118': 0,
 '003_S_4288': 0,
 '136_S_4269': 0,
 '098_S_2052': 1,
 '037_S_4214': 1,
 '027_S_0120': 0,
 '041_S_4051': 1,
 '003_S_4441': 0,
 '114_S_4379': 1,
 '116_S_0361': 1,
 '035_S_0997': 1,
 '018_S_2138': 1,
 '068_S_0210': 0,
 '031_S_2022': 1,
 '037_S_0539': 1,
 '011_S_0021': 0,
 '003_S_1057': 1,
 '068_S_4067': 1,
 '031_S_4590': 1,
 '036_S_0813': 0,
 '126_S_4507': 1,
 '073_S_2191': 1,
 '130_S_4589': 1,
 '068_S_4217': 1,
 '098_S_4215': 1,
 '109_S_4455': 1,
 '137_S_4536': 1,
 '067_S_0056': 0,
 '100_S_1226': 1,
 '072_S_4226': 1,
 '014_S_4263': 1,
 '021_S_4558': 0,
 '031_S_0830': 1,
 '094_S_2367': 1,
 '009_S_4324': 1,
 '013_S_4595': 1,
 '016_S_2031': 1,
 '137_S_0800': 1,
 '941_S_4420': 1,
 '109_S_4531': 1,
 '116_S_4483': 0,
 '031_S_4218': 0,
 '100_S_0069': 0,
 '005_S_0602': 0,
 '094_S_1417': 1,
 '073_S_4216': 1,
 '012_S_0637': 0,
 '027_S_2245': 1,
 '141_S_1004': 1,
 '126_S_1187': 1,
 '128_S_1043': 1,
 '035_S_0555': 0,
 '123_S_0113': 0,
 '014_S_4058': 1,
 '135_S_4598': 0,
 '018_S_4597': 1,
 '023_S_4448': 0,
 '126_S_2407': 1,
 '131_S_0123': 0,
 '016_S_4584': 1,
 '002_S_0729': 1,
 '021_S_4419': 1,
 '005_S_0572': 1,
 '027_S_0408': 1,
 '116_S_0657': 0,
 '023_S_4035': 1,
 '941_S_1203': 0,
 '130_S_4352': 0,
 '033_S_0906': 1,
 '073_S_0089': 0,
 '022_S_4196': 0,
 '136_S_4189': 1,
 '033_S_1098': 0,
 '018_S_0055': 0,
 '114_S_2392': 1,
 '116_S_1243': 1,
 '033_S_0920': 0,
 '068_S_2187': 1,
 '021_S_4421': 0,
 '006_S_1130': 1,
 '052_S_0952': 1,
 '021_S_0626': 1,
 '002_S_2043': 1,
 '029_S_4385': 0,
 '037_S_4381': 1,
 '137_S_4520': 0,
 '029_S_0843': 0,
 '941_S_4100': 0,
 '128_S_2036': 1,
 '153_S_2109': 1,
 '094_S_2238': 1,
 '014_S_0520': 0,
 '126_S_0709': 1,
 '135_S_4406': 1,
 '041_S_4060': 0,
 '941_S_4187': 1,
 '099_S_4480': 1,
 '072_S_4462': 1,
 '031_S_2233': 1,
 '137_S_0722': 1,
 '127_S_4148': 0,
 '031_S_4029': 1,
 '018_S_4399': 0,
 '052_S_2249': 1,
 '094_S_4282': 1,
 '072_S_4383': 1,
 '024_S_2239': 1,
 '024_S_4223': 1,
 '029_S_2395': 1,
 '072_S_1380': 1,
 '137_S_4466': 0,
 '072_S_0315': 0,
 '011_S_0023': 0,
 '006_S_4546': 1,
 '141_S_2210': 1,
 '128_S_0863': 0,
 '130_S_4605': 1,
 '141_S_1378': 1,
 '057_S_0934': 0,
 '116_S_0752': 1,
 '072_S_4131': 1,
 '116_S_4338': 1,
 '005_S_0448': 1,
 '027_S_0644': 1,
 '072_S_4206': 1,
 '032_S_0978': 1,
 '036_S_0672': 0,
 '068_S_2248': 1,
 '135_S_4676': 1,
 '131_S_0441': 0,
 '137_S_1414': 1,
 '098_S_0667': 1,
 '072_S_4610': 1,
 '023_S_0331': 1,
 '114_S_0416': 0,
 '037_S_0501': 1,
 '016_S_4009': 1,
 '021_S_2100': 1,
 '073_S_2153': 1,
 '031_S_0618': 0,
 '023_S_0061': 0,
 '116_S_4043': 0,
 '068_S_0802': 1,
 '135_S_4489': 1,
 '128_S_0770': 1,
 '130_S_0232': 0,
 '014_S_0658': 1,
 '037_S_4432': 1,
 '127_S_4301': 1,
 '009_S_4359': 1,
 '006_S_4357': 0,
 '003_S_0907': 0,
 '031_S_4024': 1,
 '022_S_4444': 1,
 '041_S_4138': 1,
 '137_S_4258': 1,
 '021_S_4402': 1,
 '012_S_1212': 0,
 '005_S_0546': 1,
 '128_S_4603': 1,
 '072_S_2070': 1,
 '002_S_4251': 1,
 '029_S_1318': 1,
 '036_S_0945': 1,
 '141_S_1052': 1,
 '041_S_1418': 1,
 '123_S_0106': 0,
 '068_S_4332': 1,
 '098_S_4201': 1,
 '002_S_0413': 0,
 '130_S_2403': 1,
 '027_S_0074': 0,
 '014_S_4039': 1,
 '128_S_0138': 1,
 '029_S_4279': 0,
 '941_S_4365': 0,
 '109_S_4260': 1,
 '041_S_4037': 0,
 '018_S_2133': 1,
 '037_S_4028': 0,
 '099_S_4104': 0,
 '053_S_4578': 0,
 '020_S_1288': 0,
 '019_S_4367': 0,
 '131_S_0384': 1,
 '135_S_4309': 1,
 '129_S_4369': 0,
 '137_S_0686': 0,
 '128_S_4571': 1,
 '099_S_2063': 1,
 '011_S_4120': 0,
 '041_S_0125': 0,
 '053_S_2357': 1,
 '137_S_0973': 1,
 '021_S_0984': 0,
 '027_S_0116': 1,
 '052_S_0951': 0,
 '014_S_4401': 0,
 '036_S_4562': 1,
 '137_S_0459': 0,
 '018_S_4696': 1,
 '023_S_4164': 0,
 '128_S_2130': 1,
 '082_S_4339': 0,
 '022_S_2379': 1,
 '014_S_4668': 1,
 '130_S_0289': 1,
 '141_S_4456': 1,
 '009_S_2381': 1,
 '053_S_4557': 1,
 '073_S_4300': 1,
 '041_S_4014': 0,
 '007_S_0101': 1}

49945

### ADNI I am Using

In [18]:
exp_path = "../data/ADNI/cleaned_gene_expression_data.csv"
exp_df = pd.read_csv(exp_path, index_col=0)
exp_df.T

gene,A1BG,A1CF,A2M,A2ML1,A3GALT2,A4GALT,A4GNT,AAAS,AACS,AACSP1,...,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3
116_S_1249,3.651,2.2865,3.039,2.3395,2.783,2.0565,2.081,7.043,3.30950,2.202,...,3.77150,4.0365,2.988,4.353000,4.739500,1.9045,5.31750,9.2190,7.3010,5.7490
037_S_4410,3.183,2.1230,3.543,2.2085,2.383,2.3490,1.733,6.773,3.27625,2.317,...,4.17300,4.4415,3.471,4.520667,4.702333,1.9265,5.38800,8.3785,6.7580,6.0935
006_S_4153,3.278,2.3545,3.528,2.1745,2.593,2.5260,1.841,6.910,3.20875,2.540,...,3.91275,4.6210,2.967,4.230667,4.545333,2.2315,5.62800,9.1085,7.3365,5.2615
116_S_1232,3.371,2.3725,3.835,2.1545,2.570,2.4720,2.249,7.209,3.24950,2.559,...,3.73800,4.4435,3.207,4.050667,4.562500,2.0545,5.46300,9.3210,7.1685,4.7340
099_S_4205,3.358,2.3865,3.392,2.1720,2.660,2.2965,1.893,6.920,3.15425,2.347,...,3.94600,4.5215,3.611,4.639667,4.890667,2.0405,5.64750,9.0300,7.2025,5.4575
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
009_S_2381,3.302,2.5075,3.524,2.2525,2.876,2.8380,2.089,6.805,3.09150,2.650,...,3.50150,4.4685,2.770,3.962333,4.472167,1.9320,5.44275,9.2900,6.7035,4.7915
053_S_4557,3.403,2.3090,3.515,2.3225,3.106,2.7715,2.102,7.265,3.27575,2.603,...,3.58325,4.1555,3.081,4.125667,4.609833,1.9445,5.14000,9.8090,7.2810,4.7055
073_S_4300,3.530,2.4155,3.651,2.0760,2.707,2.3280,2.092,7.375,3.26950,2.557,...,3.63450,4.5165,3.051,4.070333,4.733500,2.0795,5.38775,9.5215,6.9825,5.0785
041_S_4014,3.532,2.4545,3.609,2.3495,3.081,2.8230,2.024,7.257,3.11425,2.497,...,3.68525,4.0480,3.304,3.976333,4.091000,2.0075,5.05725,9.5810,6.6865,3.8660
007_S_0101,3.298,2.4120,3.804,2.1700,2.975,2.7745,1.992,6.970,3.36575,2.590,...,3.26300,3.4900,2.661,3.875000,4.362333,1.9840,4.99200,9.9225,7.2645,4.6080