In [1]:
import pandas as pd
import numpy as np
import networkx as nx

In [14]:
def generate_Bioeatures(ad_path, health_path, output:str, merge=True, sep='\t'):
    df_ad = pd.read_csv(ad_path, sep=sep, index_col=0)
    df_health = pd.read_csv(health_path, sep=sep, index_col=0)
    df_ad = df_ad.loc[:, df_ad.nunique()>1]
    df_health = df_health.loc[:, df_health.nunique()>1]
    if merge:
        df = pd.concat([df_ad.reset_index(drop=True), df_health.reset_index(drop=True)], axis=1)
        df.index = df_ad.index
        df.to_csv(output)
        return df
    else:
        df_ad.to_csv(output)
        return df_ad

In [15]:
df_adPPIpaths = generate_Bioeatures("/Users/yuxiaoxuan/master_thesis/FireGNN/AD/data/kg_rule_features/direct_features.csv",
                                    "/Users/yuxiaoxuan/master_thesis/FireGNN/AD/data/kg_rule_features/knn_features.csv",
                                    "../datasets/bioFeatures/ADPPIPaths.csv",
                                    True)

In [16]:
df_adPPIpaths

,direct_increase_AD_net,direct_decrease_AD_net,0,1,2,3,4,5,6,7,...,10,11,12,13,14,15,16,17,18,19
116_S_1249,83.551529,-13.746381,-185.559384,-6.332860,261.644358,74.031906,-425.111563,5.697771,538.601599,-56.570417,...,-24.785605,49.495452,-702.642837,362.823311,481.722996,-251.440218,22.490543,194.686100,-113.027590,-370.856676
037_S_4410,83.031632,-14.690714,-184.632607,-6.318184,269.296441,72.870252,-400.472330,5.717890,549.186881,-55.110103,...,-24.795100,48.274308,-733.686337,336.265193,476.720699,-267.887030,22.453256,197.771348,-109.515898,-344.580762
006_S_4153,82.303691,-14.079095,-183.223812,-6.257066,258.138828,73.575644,-380.921231,5.743461,538.855454,-52.655467,...,-24.819924,46.612057,-706.182620,327.417434,444.380206,-249.507938,22.652595,195.074514,-107.149133,-331.116592
116_S_1232,83.629590,-14.440381,-203.163185,-6.465757,283.716057,77.623945,-428.393195,5.886112,602.073333,-57.044556,...,-26.227006,50.093634,-748.486622,368.467692,505.605685,-280.871093,23.893225,219.641237,-122.219602,-370.606401
099_S_4205,83.280137,-15.148429,-189.011337,-6.493546,280.156133,74.985151,-449.415350,5.793352,565.783712,-57.912116,...,-25.683529,49.998650,-707.845979,363.828489,507.398258,-277.675640,23.094960,206.998127,-116.146893,-364.545504
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
009_S_2381,82.599023,-14.988810,-194.757334,-6.575576,272.950532,76.736814,-446.773406,5.830075,593.094230,-57.191023,...,-26.462707,49.259142,-782.808476,363.330419,470.233345,-264.537589,23.303371,199.348256,-118.076809,-366.254186
053_S_4557,84.311978,-14.787524,-187.575771,-6.454772,262.388620,75.093679,-439.174012,5.759864,570.807710,-55.198559,...,-25.151958,47.987303,-796.160789,351.134122,455.896935,-265.896624,22.797774,200.191749,-113.968060,-342.637801
073_S_4300,84.246519,-14.026286,-190.067073,-6.361500,267.834813,74.224290,-388.502296,5.863935,547.762637,-53.221798,...,-25.566187,47.689259,-673.293767,340.954393,462.601566,-262.956812,23.624458,207.587201,-111.655126,-330.703844
041_S_4014,81.979936,-15.031952,-192.391021,-6.449716,248.702358,72.003139,-416.223893,5.687669,526.215308,-51.156713,...,-25.128859,44.498944,-792.511349,319.593014,400.318977,-260.856673,22.837511,191.730774,-108.836228,-313.660699
007_S_0101,84.917990,-14.978048,-197.176744,-6.572876,284.898896,77.418575,-494.477072,5.817973,591.173345,-58.684876,...,-26.213804,50.046563,-783.725346,385.049278,475.780053,-303.755514,23.488603,215.844399,-121.597876,-378.209023

In [3]:
df_bp_features = generate_Bioeatures("/home/xyu/thesis/FireGNN/datasets/bioFeatures/BPsubgraphs_ad.csv",
                                     "/home/xyu/thesis/FireGNN/datasets/bioFeatures/BPsubgraphs_health.csv",
                                     "../datasets/bioFeatures/BPsubgraphs.csv",
                                     True)
df_bp_ad = generate_Bioeatures("/home/xyu/thesis/FireGNN/datasets/bioFeatures/BPsubgraphs_ad.csv",
                                     "/home/xyu/thesis/FireGNN/datasets/bioFeatures/BPsubgraphs_health.csv",
                                     "../datasets/bioFeatures/ADBPsubgraphs.csv",
                                     False)

In [4]:
df_bp_features

,"bp(GO:""response to endoplasmic reticulum stress"")","bp(GO:""calcium ion homeostasis"")","bp(GO:""response to unfolded protein"")","bp(GO:""ERK1 and ERK2 cascade"")","bp(GO:""neuron apoptotic process"")","bp(GO:""production of molecular mediator involved in inflammatory response"")","bp(MESH:""Oxidative Stress"")","bp(GO:""regulation of synaptic activity"")","bp(GO:""chronic inflammatory response"")","bp(GO:""response to oxidative stress"")","bp(GO:""immune response"")","bp(GO:""cell cycle"")","bp(GO:""microglial cell activation involved in immune response"")","bp(GOBP:""neuron differentiation"")","bp(GOBP:""neuron development"")"
116_S_1249,3.126501,-3.716402,-7.510010,25.494898,4.714764,4613.698419,-1.873451,9.725110e+12,2.851016e+17,10381.294544,6551.065858,4.753781,6.240971e+42,2.336437,1.109864
037_S_4410,3.130756,-3.604612,-7.538371,23.069878,4.610678,4997.426635,-1.539348,9.496735e+12,2.964779e+17,9724.429812,7096.975713,4.644888,6.282386e+42,2.370393,1.111965
006_S_4153,3.111451,-3.463576,-7.409673,22.778299,4.479361,4633.723071,-1.682370,9.249116e+12,2.831843e+17,9165.546258,6579.553872,4.637528,6.161329e+42,2.386719,1.113266
116_S_1232,3.141731,-3.725607,-7.611538,24.302678,4.723336,4512.178090,-2.380037,9.923888e+12,2.810105e+17,10751.215879,6406.638250,4.799964,6.482167e+42,2.409871,1.113855
099_S_4205,3.147987,-3.633550,-7.653245,24.108257,4.637622,5163.677816,-1.435496,9.915986e+12,3.082772e+17,9558.178576,7333.492483,4.720454,6.539031e+42,2.356521,1.112786
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
009_S_2381,3.155458,-3.451904,-7.703056,22.793117,4.468493,4692.865648,-2.137936,9.972789e+12,2.893247e+17,10102.725127,6663.692891,4.610881,6.623689e+42,2.394880,1.117643
053_S_4557,3.102049,-3.358305,-7.346993,22.056289,4.381344,4565.266702,-2.040173,9.608039e+12,2.866668e+17,9859.833650,6482.164614,4.583178,6.579086e+42,2.397752,1.114204
073_S_4300,3.122641,-3.610426,-7.484270,22.636452,4.616092,4728.723746,-2.110779,9.313358e+12,2.908900e+17,10380.338276,6714.706312,4.719673,6.273602e+42,2.395632,1.114553
041_S_4014,3.008457,-2.981709,-6.723048,18.915797,4.030699,4665.855652,-2.024044,9.300150e+12,2.964665e+17,8746.537573,6625.267197,4.361707,6.691362e+42,2.413264,1.115767
007_S_0101,3.128789,-3.338528,-7.525263,22.171178,4.362930,4836.763729,-1.697183,9.989106e+12,3.043479e+17,8902.682652,6868.409087,4.559141,6.862378e+42,2.385821,1.114800

In [5]:
df_bp_ad

,"bp(GO:""response to endoplasmic reticulum stress"")","bp(GO:""calcium ion homeostasis"")","bp(GO:""response to unfolded protein"")","bp(GO:""ERK1 and ERK2 cascade"")","bp(GO:""neuron apoptotic process"")","bp(GO:""production of molecular mediator involved in inflammatory response"")","bp(MESH:""Oxidative Stress"")","bp(GO:""regulation of synaptic activity"")","bp(GO:""chronic inflammatory response"")","bp(GO:""response to oxidative stress"")","bp(GO:""immune response"")","bp(GO:""cell cycle"")","bp(GO:""microglial cell activation involved in immune response"")"
116_S_1249,3.126501,-3.716402,-7.510010,25.494898,4.714764,4613.698419,-1.873451,9.725110e+12,2.851016e+17,10381.294544,6551.065858,4.753781,6.240971e+42
037_S_4410,3.130756,-3.604612,-7.538371,23.069878,4.610678,4997.426635,-1.539348,9.496735e+12,2.964779e+17,9724.429812,7096.975713,4.644888,6.282386e+42
006_S_4153,3.111451,-3.463576,-7.409673,22.778299,4.479361,4633.723071,-1.682370,9.249116e+12,2.831843e+17,9165.546258,6579.553872,4.637528,6.161329e+42
116_S_1232,3.141731,-3.725607,-7.611538,24.302678,4.723336,4512.178090,-2.380037,9.923888e+12,2.810105e+17,10751.215879,6406.638250,4.799964,6.482167e+42
099_S_4205,3.147987,-3.633550,-7.653245,24.108257,4.637622,5163.677816,-1.435496,9.915986e+12,3.082772e+17,9558.178576,7333.492483,4.720454,6.539031e+42
...,...,...,...,...,...,...,...,...,...,...,...,...,...
009_S_2381,3.155458,-3.451904,-7.703056,22.793117,4.468493,4692.865648,-2.137936,9.972789e+12,2.893247e+17,10102.725127,6663.692891,4.610881,6.623689e+42
053_S_4557,3.102049,-3.358305,-7.346993,22.056289,4.381344,4565.266702,-2.040173,9.608039e+12,2.866668e+17,9859.833650,6482.164614,4.583178,6.579086e+42
073_S_4300,3.122641,-3.610426,-7.484270,22.636452,4.616092,4728.723746,-2.110779,9.313358e+12,2.908900e+17,10380.338276,6714.706312,4.719673,6.273602e+42
041_S_4014,3.008457,-2.981709,-6.723048,18.915797,4.030699,4665.855652,-2.024044,9.300150e+12,2.964665e+17,8746.537573,6625.267197,4.361707,6.691362e+42
007_S_0101,3.128789,-3.338528,-7.525263,22.171178,4.362930,4836.763729,-1.697183,9.989106e+12,3.043479e+17,8902.682652,6868.409087,4.559141,6.862378e+42

In [16]:
ad_subgraph_features = pd.read_csv("../datasets/bioFeatures/ad_subgraph_features.csv")
ad_subgraph_features = ad_subgraph_features.loc[:, ad_subgraph_features.nunique()>1]
ad_subgraph_features

,Amyloidogenic_subgraph,GABA_subgraph,Epigenetic_modification_subgraph,Lipid_peroxidation_subgraph,Cell_cycle_subgraph,Electron_transport_chain,GSK3_subgraph,Synaptic_vesicle_endocytosis_subgraph,Plasminogen_activator_subgraph,CRH_subgraph,...,Eicosanoids_signaling_subgraph,T_cells_signaling,Regulation_of_actin_cytoskeleton_subgraph,Synapse_assembly_subgraph,Axonal_transport_subgraph,Non-amyloidogenic_subgraph,Chaperone_subgraph,Notch_signaling_subgraph,Complement_system_subgraph,Beta_secretase_subgraph
0,2228.462086,35.770792,74.532833,7.096,33.664121,43.864333,156.664307,14.724000,64.575497,93.115923,...,15.383,73.872835,245.132346,16.270192,13.844167,138.431397,83.721442,43.406096,78.435038,202.457110
1,2195.956164,28.169947,73.536667,7.920,36.321917,45.043667,161.959283,13.032667,63.022423,91.082308,...,13.942,74.581478,234.258490,15.668731,13.761333,137.974657,83.891397,43.120663,78.000346,198.591837
2,2225.103270,36.475582,77.293000,7.139,36.921912,43.602333,155.830233,14.263667,62.347521,90.121154,...,15.422,74.084597,242.538808,15.383115,13.216000,137.625113,81.882032,43.941212,76.158923,198.196172
3,2317.760847,41.268996,76.319000,6.878,35.030617,42.708000,166.109502,15.700000,65.430354,94.081462,...,15.509,75.815526,248.872215,16.314846,13.326667,141.558821,82.295346,45.320387,81.997769,201.498559
4,2232.615045,27.342374,74.108833,8.277,34.400386,43.782333,170.610233,15.449667,64.375756,89.077077,...,14.864,73.437349,244.132446,15.967308,13.272167,140.486056,83.538891,44.049178,80.527962,200.686732
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
739,2287.020740,36.010546,73.823667,7.266,33.582574,42.099667,163.477788,15.958333,64.005445,92.769462,...,15.295,72.887342,248.216006,15.650846,13.910333,139.472978,82.795679,44.556911,75.831269,201.349192
740,2192.960746,35.960640,75.531167,6.992,33.161407,43.094000,165.636192,15.633000,62.956860,89.914231,...,15.534,72.189629,247.185920,15.011923,14.138333,138.139360,82.724840,42.849616,75.781385,202.003013
741,2277.772686,35.369788,77.841667,7.343,33.615719,43.331000,160.631810,14.342667,65.022398,91.327385,...,15.540,74.819260,244.682728,15.796538,13.703333,141.453748,82.276622,43.194210,76.131308,202.005144
742,2113.041056,35.244172,77.801667,7.208,33.869919,42.158000,161.490248,16.715000,61.499932,91.453385,...,14.572,71.773110,241.195561,13.836038,14.177000,139.537523,81.138288,42.302138,73.401808,196.643452
743,2183.060563,34.059679,74.909667,7.575,33.483979,41.672333,163.337870,15.943667,64.125821,90.888462,...,15.677,77.181076,244.887090,14.888846,14.220167,138.408913,79.842346,44.253125,78.781269,200.693142

In [17]:
ad_cluster_features = pd.read_csv("../datasets/bioFeatures/ad_clutser_features.csv", index_col=0)
ad_cluster_features = ad_cluster_features.loc[:, ad_cluster_features.nunique()>1]
ad_cluster_features

,subgraph_8,subgraph_9,subgraph_11,subgraph_13,subgraph_14,subgraph_15,subgraph_16,subgraph_18,subgraph_19,subgraph_20,...,subgraph_62,subgraph_63,subgraph_64,subgraph_65,subgraph_66,subgraph_67,subgraph_68,subgraph_69,subgraph_70,subgraph_73
116_S_1249,28.080850,45.190455,23.860667,15.383,6.584667,31.031357,30.4755,23.925,25.220571,15.873000,...,212.321379,193.904826,294.830333,187.938099,121.767455,26.282667,25.752583,97.688051,37.482013,21.7950
037_S_4410,29.518617,45.008011,23.946833,13.942,6.458333,28.922143,30.5070,23.465,25.666143,15.024429,...,205.005657,183.575097,291.323815,189.541410,120.167792,27.329667,27.205583,95.318462,38.556865,20.9145
006_S_4153,29.302667,45.160420,25.322333,15.422,6.710333,29.209071,32.2235,24.069,25.883571,15.663000,...,204.108141,188.740149,298.554595,191.538288,117.125862,23.987583,27.849583,98.061231,38.441808,23.3235
116_S_1232,27.782633,45.276489,25.589833,15.509,6.708000,31.846357,29.9395,24.060,26.332714,15.698571,...,218.630081,191.650146,302.606155,191.156415,118.368792,27.992917,25.359750,100.518359,39.456423,22.8750
099_S_4205,28.179667,45.211261,24.172500,14.864,6.730667,29.268500,31.6965,24.518,25.938000,15.452143,...,211.681096,185.710574,297.915702,188.767683,121.676961,26.090083,26.083333,97.443949,38.021237,22.4250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
009_S_2381,28.892417,44.704239,24.243500,15.295,6.770333,31.030500,29.4710,24.601,25.416000,15.173571,...,211.252240,188.643146,302.634833,194.213017,119.617507,24.716000,24.782083,93.989692,39.965756,22.8180
053_S_4557,27.424450,45.997436,24.954000,15.534,6.838667,31.547143,31.1885,24.510,26.026857,16.066286,...,206.064287,186.826223,295.080935,192.008926,117.008282,26.334667,24.572417,97.177179,39.410712,23.7990
073_S_4300,28.263783,45.269057,24.632167,15.540,6.675667,31.968786,29.6300,24.164,25.890143,16.173000,...,211.633978,193.715772,295.342042,196.094361,118.720927,25.347667,24.800500,97.462410,38.190686,22.8315
041_S_4014,28.793433,45.689436,25.339500,14.572,6.857333,30.563571,29.0120,24.776,26.036857,16.495286,...,210.335728,189.490338,295.683946,190.815505,115.253644,28.119583,25.163833,94.400410,40.600853,24.7680
007_S_0101,28.926183,45.674311,24.407167,15.677,6.684667,29.839929,30.4305,25.075,25.635143,15.891857,...,208.898223,189.397346,300.387226,203.032629,116.863679,26.316333,24.843583,98.291692,39.299506,23.5140

In [18]:
health_cluster_features = pd.read_csv("../datasets/bioFeatures/health_clutser_features.csv", index_col=0)
health_cluster_features= health_cluster_features.loc[:,health_cluster_features.nunique()>1]
health_cluster_features

,subgraph_12,subgraph_14,subgraph_15,subgraph_16,subgraph_17,subgraph_18,subgraph_23,subgraph_26,subgraph_27,subgraph_28,...,subgraph_42,subgraph_43,subgraph_44,subgraph_45,subgraph_46,subgraph_47,subgraph_48,subgraph_49,subgraph_51,subgraph_52
116_S_1249,22.505083,12.616571,13.496,9.95340,15.522000,2.22575,7.4828,27.317,16.3725,29.628,...,35.846500,77.032267,14.214333,22.759083,69.409667,11.233333,24.097167,19.101744,42.22740,10.226167
037_S_4410,21.670167,13.087000,14.967,10.21185,15.451667,2.21125,7.2892,26.451,16.3125,30.516,...,32.511857,100.098367,21.771000,23.234000,69.725000,13.024000,23.767000,20.294411,38.53135,10.194167
006_S_4153,21.657250,13.005429,14.276,10.04710,15.171333,2.14600,7.4112,26.152,15.6865,29.319,...,36.123119,84.187067,13.681333,23.189417,69.898667,11.334917,22.457833,20.505744,39.02810,10.180500
116_S_1232,21.686917,12.993000,14.548,10.07540,15.456000,2.31600,7.4028,27.218,15.9120,30.486,...,34.564595,93.258700,17.594000,23.266917,74.432000,11.308083,22.942333,20.888411,42.63690,10.425833
099_S_4205,22.234417,13.175286,14.336,9.91305,15.906000,2.13700,7.2236,26.931,16.5720,29.586,...,33.526810,119.560867,17.919833,23.146000,67.294333,12.396417,23.011167,20.131744,39.73355,10.138167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
009_S_2381,22.013667,13.046857,15.068,10.13365,16.186000,2.27375,7.5248,26.512,16.0630,29.838,...,33.745119,90.622000,12.730333,23.122083,68.751500,12.787750,22.277667,20.169744,41.05215,10.249333
053_S_4557,21.596833,12.466857,14.477,10.18965,15.856333,2.41625,7.3728,26.904,16.0830,30.321,...,31.463690,104.052800,11.266000,23.127083,69.802500,13.844667,22.898333,20.596411,40.97415,10.280333
073_S_4300,21.919167,12.745286,14.485,10.39170,15.075000,2.24500,7.5244,26.164,16.2790,29.991,...,33.643833,87.711933,16.588833,23.472667,68.849667,12.010333,23.833833,21.641744,42.57970,10.271333
041_S_4014,20.023167,12.649286,15.286,10.35115,15.518667,2.43975,7.5008,27.373,13.1725,31.545,...,34.695667,106.909933,11.899167,23.288167,72.566000,13.879583,20.402000,21.171077,39.57615,10.336167
007_S_0101,21.286583,12.527429,14.468,10.11775,16.359000,2.37800,7.3200,27.104,14.6160,29.877,...,36.049214,105.881467,13.841500,23.079417,71.743167,12.336500,22.442833,20.188411,40.17475,10.352333

In [19]:
df_clusters = pd.concat([ad_cluster_features, health_cluster_features], axis=1)
df_clusters.to_csv("../datasets/bioFeatures/cluster_features.csv")

In [20]:
df_clusters.columns

Index(['subgraph_8', 'subgraph_9', 'subgraph_11', 'subgraph_13', 'subgraph_14',
       'subgraph_15', 'subgraph_16', 'subgraph_18', 'subgraph_19',
       'subgraph_20', 'subgraph_21', 'subgraph_22', 'subgraph_23',
       'subgraph_24', 'subgraph_25', 'subgraph_26', 'subgraph_27',
       'subgraph_28', 'subgraph_29', 'subgraph_33', 'subgraph_34',
       'subgraph_35', 'subgraph_36', 'subgraph_37', 'subgraph_38',
       'subgraph_39', 'subgraph_40', 'subgraph_41', 'subgraph_42',
       'subgraph_43', 'subgraph_44', 'subgraph_45', 'subgraph_46',
       'subgraph_47', 'subgraph_49', 'subgraph_50', 'subgraph_52',
       'subgraph_54', 'subgraph_55', 'subgraph_56', 'subgraph_57',
       'subgraph_58', 'subgraph_59', 'subgraph_60', 'subgraph_61',
       'subgraph_62', 'subgraph_63', 'subgraph_64', 'subgraph_65',
       'subgraph_66', 'subgraph_67', 'subgraph_68', 'subgraph_69',
       'subgraph_70', 'subgraph_73', 'subgraph_12', 'subgraph_14',
       'subgraph_15', 'subgraph_16', 'subgraph_17', 'subgraph_18',
       'subgraph_23', 'subgraph_26', 'subgraph_27', 'subgraph_28',
       'subgraph_32', 'subgraph_35', 'subgraph_36', 'subgraph_37',
       'subgraph_40', 'subgraph_41', 'subgraph_42', 'subgraph_43',
       'subgraph_44', 'subgraph_45', 'subgraph_46', 'subgraph_47',
       'subgraph_48', 'subgraph_49', 'subgraph_51', 'subgraph_52'],
      dtype='object')

In [21]:
df_subgraphs = pd.concat([ad_subgraph_features.reset_index(drop=True), health_cluster_features.reset_index(drop=True)], axis=1)
df_subgraphs.index=health_cluster_features.index
df_subgraphs.to_csv("../datasets/bioFeatures/subgraph_features.csv")

In [22]:
df_subgraphs.columns

Index(['Amyloidogenic_subgraph', 'GABA_subgraph',
       'Epigenetic_modification_subgraph', 'Lipid_peroxidation_subgraph',
       'Cell_cycle_subgraph', 'Electron_transport_chain', 'GSK3_subgraph',
       'Synaptic_vesicle_endocytosis_subgraph',
       'Plasminogen_activator_subgraph', 'CRH_subgraph',
       ...
       'subgraph_42', 'subgraph_43', 'subgraph_44', 'subgraph_45',
       'subgraph_46', 'subgraph_47', 'subgraph_48', 'subgraph_49',
       'subgraph_51', 'subgraph_52'],
      dtype='object', length=121)

In [23]:
import os
import sys
# Add parent directory to path for imports
try:
    base_dir = os.path.dirname(os.path.abspath(__file__))
except NameError:
    base_dir = os.getcwd()
sys.path.append(os.path.dirname(base_dir))
from utils.graph_utils import (
    create_fuzzy_rules,
    load_graph,
    get_kg_features,
    prepare_pyg_data,
    create_fuzzy_rules, 
    get_device,
    set_random_seeds
)

kg_features = get_kg_features("../datasets/bioFeatures/subgraph_features.csv")
print(kg_features)
kg_features.shape[1]

[[-0.46415348  0.34244466 -0.13986795 ... -1.75009412  1.05108801
  -0.73461159]
 [-1.03282163 -1.97712272 -0.62199161 ... -0.05635342 -1.5941587
  -1.2143075 ]
 [-0.52291359  0.55752697  1.1959945  ...  0.2437672  -1.23863691
  -1.41917762]
 ...
 [ 0.39850065  0.22006939  1.46153759 ...  1.85703392  1.30322757
  -0.05754081]
 [-2.4833629   0.18173466  1.44217844 ...  1.18862647 -0.84639994
   0.91434308]
 [-1.25842106 -0.17973959  0.04251143 ... -0.20688711 -0.41798455
   1.15668945]]

121

# Create BioRule Patient graphs

## Create Expression+BioRule patient graphs

In [24]:
exp=pd.read_csv("./data/adni_gene_cleaned.csv", index_col=0).T
exp

genes,A1BG,A1CF,A2M,A2ML1,A3GALT2,A4GALT,A4GNT,AAAS,AACS,AACSP1,...,ZW10,ZWILCH,ZWINT,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3
116_S_1249,3.651,2.2865,3.039,2.3395,2.783,2.25300,2.081,7.043,3.30950,2.202,...,5.748,3.77150,4.0365,4.353000,5.1763,1.9045,5.31750,9.2190,7.3010,5.7490
037_S_4410,3.183,2.1230,3.543,2.2085,2.383,2.37550,1.733,6.773,3.27625,2.317,...,5.974,4.17300,4.4415,4.520667,5.0964,1.9265,5.38800,8.3785,6.7580,6.0935
006_S_4153,3.278,2.3545,3.528,2.1745,2.593,2.46825,1.841,6.910,3.20875,2.540,...,5.119,3.91275,4.6210,4.230667,5.1143,2.2315,5.62800,9.1085,7.3365,5.2615
116_S_1232,3.371,2.3725,3.835,2.1545,2.570,2.51925,2.249,7.209,3.24950,2.559,...,4.904,3.73800,4.4435,4.050667,5.1520,2.0545,5.46300,9.3210,7.1685,4.7340
099_S_4205,3.358,2.3865,3.392,2.1720,2.660,2.39725,1.893,6.920,3.15425,2.347,...,5.533,3.94600,4.5215,4.639667,5.2103,2.0405,5.64750,9.0300,7.2025,5.4575
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
009_S_2381,3.302,2.5075,3.524,2.2525,2.876,2.76275,2.089,6.805,3.09150,2.650,...,4.523,3.50150,4.4685,3.962333,5.0892,1.9320,5.44275,9.2900,6.7035,4.7915
053_S_4557,3.403,2.3090,3.515,2.3225,3.106,2.85125,2.102,7.265,3.27575,2.603,...,5.087,3.58325,4.1555,4.125667,5.0986,1.9445,5.14000,9.8090,7.2810,4.7055
073_S_4300,3.530,2.4155,3.651,2.0760,2.707,2.38325,2.092,7.375,3.26950,2.557,...,4.938,3.63450,4.5165,4.070333,5.1731,2.0795,5.38775,9.5215,6.9825,5.0785
041_S_4014,3.532,2.4545,3.609,2.3495,3.081,2.69125,2.024,7.257,3.11425,2.497,...,4.037,3.68525,4.0480,3.976333,4.8241,2.0075,5.05725,9.5810,6.6865,3.8660
007_S_0101,3.298,2.4120,3.804,2.1700,2.975,2.52600,1.992,6.970,3.36575,2.590,...,5.172,3.26300,3.4900,3.875000,4.8604,1.9840,4.99200,9.9225,7.2645,4.6080

In [25]:
exp_subgraphs = pd.concat([exp, df_subgraphs], axis=1)
exp_subgraphs.to_csv("../datasets/bioFeatures/exp_subgraphs.csv")
exp_subgraphs

,A1BG,A1CF,A2M,A2ML1,A3GALT2,A4GALT,A4GNT,AAAS,AACS,AACSP1,...,subgraph_42,subgraph_43,subgraph_44,subgraph_45,subgraph_46,subgraph_47,subgraph_48,subgraph_49,subgraph_51,subgraph_52
116_S_1249,3.651,2.2865,3.039,2.3395,2.783,2.25300,2.081,7.043,3.30950,2.202,...,35.846500,77.032267,14.214333,22.759083,69.409667,11.233333,24.097167,19.101744,42.22740,10.226167
037_S_4410,3.183,2.1230,3.543,2.2085,2.383,2.37550,1.733,6.773,3.27625,2.317,...,32.511857,100.098367,21.771000,23.234000,69.725000,13.024000,23.767000,20.294411,38.53135,10.194167
006_S_4153,3.278,2.3545,3.528,2.1745,2.593,2.46825,1.841,6.910,3.20875,2.540,...,36.123119,84.187067,13.681333,23.189417,69.898667,11.334917,22.457833,20.505744,39.02810,10.180500
116_S_1232,3.371,2.3725,3.835,2.1545,2.570,2.51925,2.249,7.209,3.24950,2.559,...,34.564595,93.258700,17.594000,23.266917,74.432000,11.308083,22.942333,20.888411,42.63690,10.425833
099_S_4205,3.358,2.3865,3.392,2.1720,2.660,2.39725,1.893,6.920,3.15425,2.347,...,33.526810,119.560867,17.919833,23.146000,67.294333,12.396417,23.011167,20.131744,39.73355,10.138167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
009_S_2381,3.302,2.5075,3.524,2.2525,2.876,2.76275,2.089,6.805,3.09150,2.650,...,33.745119,90.622000,12.730333,23.122083,68.751500,12.787750,22.277667,20.169744,41.05215,10.249333
053_S_4557,3.403,2.3090,3.515,2.3225,3.106,2.85125,2.102,7.265,3.27575,2.603,...,31.463690,104.052800,11.266000,23.127083,69.802500,13.844667,22.898333,20.596411,40.97415,10.280333
073_S_4300,3.530,2.4155,3.651,2.0760,2.707,2.38325,2.092,7.375,3.26950,2.557,...,33.643833,87.711933,16.588833,23.472667,68.849667,12.010333,23.833833,21.641744,42.57970,10.271333
041_S_4014,3.532,2.4545,3.609,2.3495,3.081,2.69125,2.024,7.257,3.11425,2.497,...,34.695667,106.909933,11.899167,23.288167,72.566000,13.879583,20.402000,21.171077,39.57615,10.336167
007_S_0101,3.298,2.4120,3.804,2.1700,2.975,2.52600,1.992,6.970,3.36575,2.590,...,36.049214,105.881467,13.841500,23.079417,71.743167,12.336500,22.442833,20.188411,40.17475,10.352333

In [26]:
exp_subgraphs.shape

(744, 19221)

In [29]:
exp_clusters = pd.concat([exp, df_clusters], axis=1)
exp_clusters.to_csv("../datasets/bioFeatures/exp_clusters.csv")
exp_clusters

,A1BG,A1CF,A2M,A2ML1,A3GALT2,A4GALT,A4GNT,AAAS,AACS,AACSP1,...,subgraph_42,subgraph_43,subgraph_44,subgraph_45,subgraph_46,subgraph_47,subgraph_48,subgraph_49,subgraph_51,subgraph_52
116_S_1249,3.651,2.2865,3.039,2.3395,2.783,2.25300,2.081,7.043,3.30950,2.202,...,35.846500,77.032267,14.214333,22.759083,69.409667,11.233333,24.097167,19.101744,42.22740,10.226167
037_S_4410,3.183,2.1230,3.543,2.2085,2.383,2.37550,1.733,6.773,3.27625,2.317,...,32.511857,100.098367,21.771000,23.234000,69.725000,13.024000,23.767000,20.294411,38.53135,10.194167
006_S_4153,3.278,2.3545,3.528,2.1745,2.593,2.46825,1.841,6.910,3.20875,2.540,...,36.123119,84.187067,13.681333,23.189417,69.898667,11.334917,22.457833,20.505744,39.02810,10.180500
116_S_1232,3.371,2.3725,3.835,2.1545,2.570,2.51925,2.249,7.209,3.24950,2.559,...,34.564595,93.258700,17.594000,23.266917,74.432000,11.308083,22.942333,20.888411,42.63690,10.425833
099_S_4205,3.358,2.3865,3.392,2.1720,2.660,2.39725,1.893,6.920,3.15425,2.347,...,33.526810,119.560867,17.919833,23.146000,67.294333,12.396417,23.011167,20.131744,39.73355,10.138167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
009_S_2381,3.302,2.5075,3.524,2.2525,2.876,2.76275,2.089,6.805,3.09150,2.650,...,33.745119,90.622000,12.730333,23.122083,68.751500,12.787750,22.277667,20.169744,41.05215,10.249333
053_S_4557,3.403,2.3090,3.515,2.3225,3.106,2.85125,2.102,7.265,3.27575,2.603,...,31.463690,104.052800,11.266000,23.127083,69.802500,13.844667,22.898333,20.596411,40.97415,10.280333
073_S_4300,3.530,2.4155,3.651,2.0760,2.707,2.38325,2.092,7.375,3.26950,2.557,...,33.643833,87.711933,16.588833,23.472667,68.849667,12.010333,23.833833,21.641744,42.57970,10.271333
041_S_4014,3.532,2.4545,3.609,2.3495,3.081,2.69125,2.024,7.257,3.11425,2.497,...,34.695667,106.909933,11.899167,23.288167,72.566000,13.879583,20.402000,21.171077,39.57615,10.336167
007_S_0101,3.298,2.4120,3.804,2.1700,2.975,2.52600,1.992,6.970,3.36575,2.590,...,36.049214,105.881467,13.841500,23.079417,71.743167,12.336500,22.442833,20.188411,40.17475,10.352333

## NormEXpressionSubgraph graph

In [7]:
import os
import torch
import torch.nn.functional as F
import numpy as np
import sys

# Add parent directory to path for imports
try:
    base_dir = os.path.dirname(os.path.abspath(__file__))
except NameError:
    base_dir = os.getcwd()
sys.path.append(os.path.dirname(base_dir))
from utils.graph_utils import (
    create_fuzzy_rules,
    load_graph,
    get_kg_features,
    prepare_pyg_data,
    create_fuzzy_rules, 
)

from fuzzy_models.fuzzy_models import get_fuzzy_model
from tqdm import trange

In [8]:
G = load_graph("../datasets/two_classes/no_label_leakage/G_NormExpressionSubgraph_k10.pkl")
kg_features = get_kg_features("../datasets/bioFeatures/subgraph_features.csv")
print(kg_features.shape)
data=prepare_pyg_data(G=G,
                        kg_feature_path="../datasets/bioFeatures/subgraph_features.csv",
                        kg_features=True,
                        topological_features=False)

#print(data)

in_channels = data.x.size(1)
out_channels = int(data.y.max().item() + 1)
num_rules = kg_features.shape[1]
# prepare input for training
model = get_fuzzy_model(
    model_type='gcn',
    in_channels=in_channels,
    hidden_channels=128,
    out_channels=out_channels,
    num_rules=num_rules
)

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.005,
    weight_decay=5e-4
)

topo_features_np = data.topo_features.cpu().numpy()

centers, widths = create_fuzzy_rules(
topo_features_np,
num_rules=model.num_rules
)

with torch.no_grad():
    model.fuzzy_layer.centers.copy_(
        torch.tensor(centers, dtype=torch.float)
    )
    model.fuzzy_layer.log_sigmas.copy_(
        torch.log(torch.tensor(widths, dtype=torch.float))
    )
    
# train
for epoch in trange(200, desc="Training"):
        model.train()
        optimizer.zero_grad()

        out, _ = model(
            data.x,
            data.edge_index,
            topo_features=data.topo_features
        )

        loss = F.nll_loss(out[data.train_mask], data.y[data.train_mask])
        loss.backward()
        optimizer.step()

Loaded graph from ../datasets/two_classes/no_label_leakage/G_NormExpressionSubgraph_k10.pkl: 121 nodes, 600 edges
(744, 121)

Training:   0%|          | 0/200 [00:00<?, ?it/s]

RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 121 but got size 744 for tensor number 1 in the list.

In [11]:
G.number_of_nodes()

121